[project]
name = "civica-ai"
version = "4.0.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi==0.117.1",
    "uvicorn[standard]==0.36.0",
    "python-multipart==0.0.20",
    "pypdf",
    "python-dotenv",
    "pillow",
    "requests==2.32.5",
    "beautifulsoup4==4.13.5",
    "pydantic==2.12.5",
    "langgraph==1.0.10",
    "google-genai==2.23.0",
    "openai==3.13.0",
]

[tool.vercel]
entrypoint = "api:app"
